-- MySQL Script generated by MySQL Workbench
-- Tue Nov  3 12:45:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gruppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gruppe` (
  `GID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `NID` INT NOT NULL DEFAULT Gruppen Admin,
  PRIMARY KEY (`GID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mitglieder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mitglieder` (
  `MID` INT NOT NULL AUTO_INCREMENT,
  `NID` INT NOT NULL,
  `GID` INT NOT NULL,
  `Datum` DATETIME NOT NULL,
  `Gruppe_GID` INT NOT NULL,
  PRIMARY KEY (`MID`, `Gruppe_GID`),
  INDEX `fk_Mitglieder_Gruppe1_idx` (`Gruppe_GID` ASC) VISIBLE,
  CONSTRAINT `fk_Mitglieder_Gruppe1`
    FOREIGN KEY (`Gruppe_GID`)
    REFERENCES `mydb`.`Gruppe` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bilder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bilder` (
  `BID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Kategorie` VARCHAR(45) NOT NULL,
  `Inhaltsbeschreibung` VARCHAR(45) NOT NULL,
  `Data` BLOB NOT NULL,
  PRIMARY KEY (`BID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nachricht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nachricht` (
  `NAID` INT NOT NULL AUTO_INCREMENT,
  `NID` INT NOT NULL,
  `Nachricht` INT NOT NULL,
  `Datum` DATETIME NOT NULL,
  PRIMARY KEY (`NAID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blog` (
  `BID` INT NOT NULL AUTO_INCREMENT,
  `NID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Nachricht_NAID` INT NOT NULL,
  PRIMARY KEY (`BID`, `Nachricht_NAID`),
  INDEX `fk_Blog_Nachricht1_idx` (`Nachricht_NAID` ASC) VISIBLE,
  CONSTRAINT `fk_Blog_Nachricht1`
    FOREIGN KEY (`Nachricht_NAID`)
    REFERENCES `mydb`.`Nachricht` (`NAID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nutzer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nutzer` (
  `NID` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(45) NOT NULL,
  `Nachname` VARCHAR(45) NOT NULL,
  `Klasse` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Geburtsdatum` DATETIME NOT NULL,
  `Bilder_BID` INT NOT NULL,
  `Mitglieder_MID` INT NOT NULL,
  `Bilder_BID1` INT NOT NULL,
  `Blog_BID` INT NOT NULL,
  PRIMARY KEY (`NID`, `Mitglieder_MID`, `Bilder_BID1`, `Blog_BID`),
  INDEX `fk_Nutzer_Mitglieder1_idx` (`Mitglieder_MID` ASC) VISIBLE,
  INDEX `fk_Nutzer_Bilder1_idx` (`Bilder_BID1` ASC) VISIBLE,
  INDEX `fk_Nutzer_Blog1_idx` (`Blog_BID` ASC) VISIBLE,
  CONSTRAINT `fk_Nutzer_Mitglieder1`
    FOREIGN KEY (`Mitglieder_MID`)
    REFERENCES `mydb`.`Mitglieder` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nutzer_Bilder1`
    FOREIGN KEY (`Bilder_BID1`)
    REFERENCES `mydb`.`Bilder` (`BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nutzer_Blog1`
    FOREIGN KEY (`Blog_BID`)
    REFERENCES `mydb`.`Blog` (`BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
