package de.its.fti1;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;

/**
 *
 * @author FTI1
 */
public class GUI extends javax.swing.JFrame {

    private Person[] personen;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.erzeugeDaten();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPersonen = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGirokonten = new javax.swing.JList();
        btAbrechnen = new javax.swing.JButton();
        pnlSteuerung = new javax.swing.JPanel();
        btEinzahlen = new javax.swing.JButton();
        btAuszahlen = new javax.swing.JButton();
        btÜberweisen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfBetrag = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kontoverwaltung");

        lstPersonen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPersonen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPersonenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPersonen);

        jLabel1.setText("Personen");

        jLabel2.setText("Konten der Person");

        lstGirokonten.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstGirokonten);

        btAbrechnen.setText("abrechnen");

        pnlSteuerung.setLayout(new java.awt.GridLayout(2, 3, 5, 0));

        btEinzahlen.setText("einzahlen");
        pnlSteuerung.add(btEinzahlen);

        btAuszahlen.setText("auszahlen");
        pnlSteuerung.add(btAuszahlen);

        btÜberweisen.setText("überweisen");
        pnlSteuerung.add(btÜberweisen);

        jLabel3.setText("Betrag");
        pnlSteuerung.add(jLabel3);

        tfBetrag.setText("10.00");
        pnlSteuerung.add(tfBetrag);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(pnlSteuerung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btAbrechnen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSteuerung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAbrechnen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPersonenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPersonenValueChanged
        // TODO add your handling code here:
        lstGirokonten.setListData(personen[evt.getFirstIndex()].getKonten());
    }//GEN-LAST:event_lstPersonenValueChanged

    private void erzeugeDaten() {
        personen = new Person[5];
        personen[0] = new Person(1, "Meier", "Franz");
        personen[0].addKonto(new Girokonto(11, 500.0, 0.99));
        personen[0].addKonto(new Sparkonto(12, 2.0));
        personen[0].addKonto(new Festgeldkonto(13, 6, 1000));
        personen[1] = new Person(2, "Müller", "Hans");
        personen[1].addKonto(new Girokonto(22, 1500.0, 0.99));
        personen[2] = new Person(3, "Schmitz", "Klaus");
        personen[2].addKonto(new Girokonto(33, 2500.0, 0.99));
        personen[3] = new Person(4, "Holz", "Manfred");
        personen[3].addKonto(new Girokonto(44, 3500.0, 0.25));
        personen[4] = new Person(5, "Klemm", "Sigfried");
        personen[4].addKonto(new Girokonto(55, 4500.0, 0.25));
        
        ArrayList<Person> p = new ArrayList<>(Arrays.asList(personen));
        
        lstPersonen.setListData(personen);
        for (Person person : personen) {
            System.out.println(person.toString());
            for (Konto konto : person.getKonten()) {
                System.out.println("   - " + konto.getTyp());
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrechnen;
    private javax.swing.JButton btAuszahlen;
    private javax.swing.JButton btEinzahlen;
    private javax.swing.JButton btÜberweisen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstGirokonten;
    private javax.swing.JList lstPersonen;
    private javax.swing.JPanel pnlSteuerung;
    private javax.swing.JTextField tfBetrag;
    // End of variables declaration//GEN-END:variables
}
